Importar o Dataset e selcionar as colunas que serão usadas.

In [76]:
import pandas as pd

melbourne_file_path = '/home/bruno/Documents/Python/100DaysChallenge/python/input/melb_data.csv'
melbourne_data = pd.read_csv(melbourne_file_path) 
melbourne_data.columns

Index(['Unnamed: 0', 'Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method',
       'SellerG', 'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom',
       'Car', 'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea',
       'Lattitude', 'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

Verificar os nomes das colunas

## Imprime a lista de colunas do dataset

In [77]:
melbourne_data.columns

Index(['Unnamed: 0', 'Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method',
       'SellerG', 'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom',
       'Car', 'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea',
       'Lattitude', 'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

## Carregar na variável y os dados da coluna salesprice

In [78]:
y = melbourne_data.Price 
print(y)

0        1480000.0
1        1035000.0
2        1465000.0
3         850000.0
4        1600000.0
           ...    
18391     622500.0
18392    2500000.0
18393    1100000.0
18394    1285000.0
18395    1050000.0
Name: Price, Length: 18396, dtype: float64


## Escolhendo lista de colunas ou atributos de um data set

In [82]:
melbourne_features = ['Rooms', 'Bathroom', 'Landsize', 'Lattitude', 'Longtitude']


## Criar uma lista de atributos em X, que é o novo dataset (filtrado)

In [83]:
X = melbourne_data[melbourne_features]
print(X)

       Rooms  Bathroom  Landsize  Lattitude  Longtitude
0          2       1.0     202.0  -37.79960   144.99840
1          2       1.0     156.0  -37.80790   144.99340
2          3       2.0     134.0  -37.80930   144.99440
3          3       2.0      94.0  -37.79690   144.99690
4          4       1.0     120.0  -37.80720   144.99410
...      ...       ...       ...        ...         ...
18391      2       2.0       NaN  -37.86393   144.90484
18392      4       1.0     866.0  -37.85908   144.89299
18393      4       3.0       NaN  -37.72006   145.10547
18394      4       1.0     362.0  -37.81188   144.88449
18395      4       2.0       NaN  -37.81829   144.87404

[18396 rows x 5 columns]


## Resumo do data set

In [84]:
X.describe()

Rooms      Bathroom       Landsize     Lattitude    Longtitude
count  18396.000000  14925.000000   13603.000000  15064.000000  15064.000000
mean       2.935040      1.538492     558.116371    -37.809849    144.996338
std        0.958202      0.689311    3987.326586      0.081152      0.106375
min        1.000000      0.000000       0.000000    -38.182550    144.431810
25%        2.000000      1.000000     176.500000    -37.858100    144.931193
50%        3.000000      1.000000     440.000000    -37.803625    145.000920
75%        3.000000      2.000000     651.000000    -37.756270    145.060000
max       12.000000      8.000000  433014.000000    -37.408530    145.526350

## Pega as primeiras linhas do DataSet

In [85]:
X.head()

Rooms  Bathroom  Landsize  Lattitude  Longtitude
0      2       1.0     202.0   -37.7996    144.9984
1      2       1.0     156.0   -37.8079    144.9934
2      3       2.0     134.0   -37.8093    144.9944
3      3       2.0      94.0   -37.7969    144.9969
4      4       1.0     120.0   -37.8072    144.9941

## Criando seu modelo

Utiliza-se a biblioteca scikit-learn para criar modelos. Essa biblioteca é escrita como sklearn. É a mais popular para modelar os tipos de dados armazenados em DataFrames.

Os passos para construir e usar um modelo são:
* Definir: Que tipo de modelo será? Uma árvore de decisão? Outro tipo de modelo? Alguns parâmetros do modelos também säo especificados. 
* Modelar: Capturar padrões dos dados. Este será o coração do modelo.
* Predizer: Autoexplicativo.
* Avaliar: Determinar o quão acurado é o modelo de predição. 

In [18]:
import numpy as np
np.isnan(X) # Cria uma máscara True e False para descobrir valores Nan, onde True = NaN


Rooms  Bathroom  Landsize  Lattitude  Longtitude
0      False     False     False      False       False
1      False     False     False      False       False
2      False     False     False      False       False
3      False     False     False      False       False
4      False     False     False      False       False
...      ...       ...       ...        ...         ...
18391  False     False      True      False       False
18392  False     False     False      False       False
18393  False     False      True      False       False
18394  False     False     False      False       False
18395  False     False      True      False       False

[18396 rows x 5 columns]

In [19]:
np.where(np.isnan(X)) # Verifica a posição cartesiana dos NaNs, retornando uma tupla.

(array([    8,     8,     8, ..., 18391, 18393, 18395]),
 array([1, 2, 3, ..., 2, 2, 2]))

In [42]:
# Substitui NaN por 0
np.nan_to_num(X)

#Outras opçÕes para substituir Nan
#sklearn.impute.SimpleImputer: Preenche com a mediana ou média
# pd.DataFrame(X).fillna() : Se precisar de outra coisa que não zeros.

NameError: name 'sklearn' is not defined

## Limpeza NaN

In [86]:
X.isnull().sum()


Rooms            0
Bathroom      3471
Landsize      4793
Lattitude     3332
Longtitude    3332
dtype: int64

In [89]:
from sklearn.tree import DecisionTreeRegressor

# Define model. Specify a number for random_state to ensure same results each run
melbourne_model = DecisionTreeRegressor(random_state=1)

# Fit model
melbourne_model.fit(X,y)

ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

Muitos modelos de ML permitem alguma aleatoriaedade nos modelos de treino. Especificando um número para o random_state, garante que terá o mesmo resultado em cada rodada e isto é considerado uma  boa prática. Pode usar qualquer valor e a qualidade do modelo náo dependerá significantemente do valor exato escolhido. 
Agora existe um modelo apurado que pode ser usado para fazer predições.

## Fazendo predições

Na prática, queremos fazer predições para novas casas, que virão ao mercado, ao invés das casas que já temos o preço. Mas iremos fazer a predição das primeiras linhas dos dados de treino para ver o quanto essa função funciona.

In [28]:
print("Making predictions for the following 5 houses:")
print(X.head())
print("The predictions are")
print(melbourne_model.predict(X.head()))

Making predictions for the following 5 houses:
   Rooms  Bathroom  Landsize  Lattitude  Longtitude
0      2       1.0     202.0   -37.7996    144.9984
1      2       1.0     156.0   -37.8079    144.9934
2      3       2.0     134.0   -37.8093    144.9944
3      3       2.0      94.0   -37.7969    144.9969
4      4       1.0     120.0   -37.8072    144.9941
The predictions are
[1480000. 1035000. 1465000.  850000. 1600000.]


## Validando o modelo

* A validação de um modelo, serve para verificar o qual bom ele é. E na maioria dos casos, para saber se um modelo é bom, precisamos medir sua acurácia.

* Muitas pessoas cometem o erro de utilizar os dados de treino para testar o modelo, mas isso é um erro. (Nota Bruno: Acredito que isso causará um viés de afirmação, pois se utilizar os mesmos dados treinados, na teoria o resultado seria o mesmo.)

* Existem diversas formas de resumir a qualidade de um modelo de uma forma compreensível, vamos começar pelo MAE - Mean Absolut Error.

* O erro significa: erro = Atual - previsto. Por exemplo se o valor atual de uma casa é 150.000 e o previsto era de 100.000, então o erro é de 50.000. Com a métrica MAE temos o valor absoluto de cada erro, convertendo cada erro em um valor positivo e podemos então pegar a média desses erros e essa será a medidade de qualidade. Isto é, na média nossas previsões estão X% fora da média.

* Então uma vez tendo um modelo, podemos calcular o MAE da seguinte forma:

In [30]:
from sklearn.metrics import mean_absolute_error

predicted_home_prices = melbourne_model.predict(np.nan_to_num(X))

mean_absolute_error(y, predicted_home_prices) 

65623.27469991957

* Quando se utiliza os mesmos dados para treinar um modelo e par avaliá-lo, pode se ao fim obter uma acurácia muito baixa, pois o algoritmo de ML, irá encontrar padrões nos dados. Com isso, pode ser que no data set tenha um padrão que todas as casas de porta verde sejam mais caras, mas que essa influência de fato não exista e foi só uma coinscidência da amostra utilizada. Depois ao receber novos dados o modelo pode ter uma baixa acurácia, por causa deste padrão encontrado e validado.

* A biblioteca scikit-learn tem uma função chamada train_test_split, que divide o dataset em duas partes. E iremos utilizar parte dos dados para treinar e desenhar o modelo, e outra parte para validar e calcular o mean_absolut_error.

## Separar dados de treino e validação

In [35]:
from sklearn.model_selection import train_test_split

X2 = np.nan_to_num(X)
# split data into training and validation data, for both features and target
# The split is based on a random number generator. Supplying a numeric value to
# the random_state argument guarantees we get the same split every time we
# run this script.
train_X, val_X, train_y, val_y = train_test_split(X2, y, random_state = 0)
# Define model
melbourne_model = DecisionTreeRegressor()
# Fit model
melbourne_model.fit(train_X, train_y)

# get predicted prices on validation data
val_predictions = melbourne_model.predict(val_X)
print(mean_absolute_error(val_y, val_predictions))

274754.84613250894
